[tool.poetry]
name = "dj-orm-to-dto"
version = "0.1.0"
description = ""
authors = ["AlexandrZhydyk <zhydykalex@ukr.net>"]
readme = "README.md"
packages = [{include = "dj_orm_to_dto"}]

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.2.2"
flake8 = "^6.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
